#!/usr/bin/env bash
# Regenerates the 20 container widget providers, their labels and their manifest receivers.
set -euo pipefail

COUNT=20
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/app/src/main"
PROVIDERS_FILE="$APP/java/org/micoli/coverwidgetcontainer/cover/ContainerProviders.kt"
LABELS_FILE="$APP/res/values/container_labels.xml"
MANIFEST_FILE="$APP/AndroidManifest.xml"

{
  echo "package org.micoli.coverwidgetcontainer.cover"
  echo
  echo "// Generated by scripts/gen_providers.sh"
  for i in $(seq 1 "$COUNT"); do
    printf 'class Container%02dProvider : ContainerWidgetProvider()\n' "$i"
  done
} > "$PROVIDERS_FILE"

{
  echo '<?xml version="1.0" encoding="utf-8"?>'
  echo '<!-- Generated by scripts/gen_providers.sh -->'
  echo '<resources>'
  for i in $(seq 1 "$COUNT"); do
    printf '    <string name="container_label_%02d">Container %d</string>\n' "$i" "$i"
  done
  echo '</resources>'
} > "$LABELS_FILE"

RECEIVERS="$(mktemp)"
for i in $(seq 1 "$COUNT"); do
  n="$(printf '%02d' "$i")"
  cat >> "$RECEIVERS" <<EOF
        <receiver
            android:name=".cover.Container${n}Provider"
            android:exported="true"
            android:label="@string/container_label_${n}">
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
            </intent-filter>
            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@xml/container_widget_info" />
            <meta-data
                android:name="com.samsung.android.appwidget.provider"
                android:resource="@xml/samsung_container_widget_info" />
        </receiver>
EOF
done

RECEIVERS="$RECEIVERS" perl -0pi -e '
  open my $f, "<", $ENV{RECEIVERS} or die;
  my $r = do { local $/; <$f> };
  close $f;
  s{(<!-- BEGIN GENERATED RECEIVERS -->\n).*?(\s*<!-- END GENERATED RECEIVERS -->)}{$1$r$2}s
' "$MANIFEST_FILE"

rm -f "$RECEIVERS"
echo "Generated $COUNT providers."
